### ISSUE TITLE
[Correção] RF009 - Gestão de Autores

### ISSUE THREAD

**Issue by cmaffort** [cmaffort/SGAB#7]
**No projeto sgab-core:**

- Classe import jdk.jfr.Experimental não existe na versão 8 do JDK, então não deveria ser inserida.
- As classes inseridas no projeto sgab-core não compilam. Não é permitido quebrar o build do branch principal.
- Classe de serviço NÃO é uma classe DAO, então GestaoAutor não deve implementar GestaoAutorDAO.
- Classe AutorHelper acessa métodos que sequer existem na classe Autor, que vocês mesmos implementaram!
- Classe DTO (Autor) não é uma classe DAO. Então não é necessário que ela implemente uma interface DAO.

**No projeto sgab-view-web:**

-Deve-se usar as folhas de estilo da pasta web\css. Qual a lógica de cada tela ter uma folha de estilos?
-A página cadastro-de-autores.html não está realizando as funções esperadas.

**Issue:** Corrigir os problemas apontados acima.

**Comment by marcosazevedo2112** [comment]
Os problemas apontados a cima foram corrigidos, abrimos um novo PR.
Obrigado
